/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    Header: typeof import('./src/components/Header.vue')['default']
    Imgload: typeof import('./src/components/widget/imgload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Sidetool: typeof import('./src/components/widget/sidetool.vue')['default']
  }
}
